version: '3'

services:
  #database
  db: 
    image: mariadb:latest
    container_name: db
    # data persistence
    volumes: 
      - db_data:/var/lib/mysql
    # when server reboots the server will restart
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # wordpress
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    # depends on keeps the wordpress from starting before the db will start
    depends_on:
      - db
      - phpmyadmin
    image: wordpress:latest
    ports: 
      - '8081:80'
    restart: always
    volumes: 
      - './html:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
